# Dictionaries

The Python dict type consists of key:value pairs.

## Lets start out with a list whose items are tuples

In [ ]:
people = [
    (1112, "robert disalvo"),
    (3001, "janice blinoff"),
    (1234, "gabor szabo"),
    (9123, "mihir ali")
    ]

In [ ]:
print(people)

In [ ]:
print(people[1][0])

## Let's search the list for a specific four-digit search key

In [ ]:
search_key = int(input("Enter a four-digit search key: "))

found = False
for item in people:   # Each item in the list is a tuple (key, value)
    if (item[0] == search_key):
        found = True
        break

## If the key is found print the key and the corresponding name
* Otherwise ask if the user wants to add the new key to the list

In [ ]:
if found:
    print(f"\nI found {search_key} in our database with the name '{item[1]}'")
else:
    ans = input(f"\n{search_key} is not in our database.  "
                f"Would you like to add it Y/N? ")
    if ans[0].upper() == 'Y':
        name = input(f"what name should we associate with {search_key}? ")
        people.append((search_key, name))

In [ ]:
people

## This is the entire program for your study and experimentation:

In [ ]:
people = [
    (1112, "robert disalvo"),
    (3001, "janice blinoff"),
    (1234, "estandia fromm"),
    (5192, "gabor szabo"),
    (9123, "mihir ali")
    ]

search_key = int(input("Enter a four-digit search key: "))

found = False
for item in people:
    if item[0] == search_key:
        found = True
        break

if found:
    print(f"\nI found {search_key} in our database with the name '{item[1]}'")
else:
    ans = input(f"\n{search_key} is not in our database.  "
                f"Would you like to add it? ")
    if ans[0].upper() == 'Y':
        name = input(f"what name should we associate with {search_key}? ")
        people.append((search_key, name))

print(f"\nthe list is currently: \n{str(people)}")

### This kind of database search is common in our world.   
* The data structure above has some weaknesses.  
 * For example it allows two individuals with the same id number.   
 * It run a lot of code to find the person from the people list.
 * The time that it takes to find a specific key is proportional to the number items in the list
 * Do we keep the list sorted, if so how do we "insert" new items?

## Dictionaries consist of Key-Value Pairs

The Python dict type looks much like a list of tuples (key, value)  
* Every item in a dictionary is a pair, ***key : value***
* The first item of the pair is always the key and it must be unique.  
 * You cannot have two items in a dictionary with the same key. 
 * The key must be immutable. (a tuple could be used as a key but not a list -- tuples, as we know, are immutable, while lists are mutable.)
 * What happens if we attempt to add a key/value pair with a key that already exists?
  * The value associated the the key is changed
* The second part of the key/value pair is the **value**.  
 * The same value can appear in more than one key-value pair in the dictionary.  
 * The value can be any Python object type
 * The value can be mutable or immutable

### You instantiate a dictionary using curly braces, { }, colons :, and commas, as follows:

In [ ]:
people = {
    1112: "robert disalvo",
    3001: "janice blinoff",
    1234: "estandia fromm",
    5192: "gabor szabo",
    9123: "mihir ali"
    }

# or

working_dict = {}      # an empty dictionary object
print(f"The type of people is {type(people)}")
working_dict = dict()
print(f"The type of working_dict is {type(working_dict)}")

In [ ]:
# What does this give you?
working = {2}
print(f"The type of working is {type(working)}")

### Back to dictionaries

In [ ]:
people = {
    1112: "robert disalvo",
    3001: "janice blinoff",
    1234: "estandia fromm",
    5192: "gabor szabo",
    9123: "mihir ali"
    }
working_dict = {}
print('People ', people, '\n')
print('working_dict ', working_dict)

You insert items (new pairs) into a dictionary using the brackets notation:

In [ ]:
people[9998] = "frank lewis"      # inserts

You access the value of an item in a dictionary using the brackets notation:

In [ ]:
print(people[9998])  # the key is in the []

You mutate an element already in a dictionary by changing its value (i.e., second component) using the bracket notation:

In [ ]:
people[1112] = "kimberly lewis"   # overwrites

In [ ]:
print(people[1112])  # remember 1112 is the key, not an index value

You can not access a dictionary item by giving an index from 0 to the size of the dictionary like you do with a list or tuple.

In [ ]:
# wrong -- will raise (throw) a runtime "KeyError" exception
print ("The first two items in the dictionarly are NOT ",
        people[0]," and ", people[1] )

What does KeyError mean in this case?

Instead, dictionaries are accessed only through the key in the pair -- even if that key is not an int.

In [ ]:
working_dict = {
    "AB 709"  : "charter schools (vetoed)",
    "AB 2009" : "CSU Campuses (vetoed)",
    "AB 2329" : "computer education (signed)",
    "SB 799"  : "reserive limitation (in process)"
    }
   
working_dict["AB 2548"] = "new accountability system  (in process)"
print(working_dict["AB 2009"])

Here we are going to loop through the tuple we created earlier

In [ ]:
people = {
    1112: "robert disalvo",
    3001: "janice blinoff",
    1234: "estandia fromm",
    5192: "gabor szabo",
    9123: "mihir ali"
    }

for key in people:
    print(key)

You can loop through dictionaries, but what you get when using the for loop **for item in my_dictionary:** statement, is **an item** not a key/pair, but the **key** -- from the key:value pair. You can use the key to get the value.

Refactor the ID/Name Example from a tuple to a dict

Now we'll see how to write the search_key example from the previous section using dictionaries rather than a list of tuples.

In [ ]:
# a list of tuples
people = [
    (1112, "robert disalvo"),
    (3001, "janice blinoff"),
    (1234, "estandia fromm"),
    (5192, "gabor szabo"),
    (9123, "mihir ali")
    ]

If we run the following **for loop** what will be the output?    
* people is a list of tuples

In [ ]:
for item in people:
    print(item)

In [ ]:
# a dict, the key in an int (imutable) and the value is a string
people = {
    1112: "robert disalvo",
    3001: "janice blinoff",
    1234: "estandia fromm",
    5192: "gabor szabo",
    9123: "mihir ali"
    }

If we run the following for loop what will be the output?    
* people is now a dict

In [ ]:
for item in people:
    print(item)

We get only the **key**

But we can use the **key** to get the **value**

In [ ]:
for key in people:
    print(key, people[key])

## the values() method

In [ ]:
for item in people.values():
    print(item)

Next  we will see how to write the search_key example from the previous section using dictionaries rather than a list of tuples.

In [2]:
people = {
    1112: "robert disalvo",
    3001: "janice blinoff",
    1234: "estandia fromm",
    5192: "gabor szabo",
    9123: "mihir ali"
    }

In [4]:
search_key = int(input("Enter a four-digit search key: "))

if search_key in people:
    print(f"\nI found {search_key} in our database "
          f"with the name '{people[search_key]}'")
else:
    ans = input(f"\n{search_key} is not in our database.  "
                f"Would you like to add it (Y/N)? ")
    if ans[0].upper() == 'Y':
        name = input(f"what name should we associate with {search_key}? ")   
        people[search_key] = name

Enter a four-digit search key: 5000

5000 is not in our database.  Would you like to add it (Y/N)? yes
what name should we associate with 5000? Gary Stillman


We can print the dictionary by simply using print()

In [5]:
print(people)

{1112: 'robert disalvo', 3001: 'janice blinoff', 1234: 'estandia fromm', 5192: 'gabor szabo', 9123: 'mihir ali', 5000: 'Gary Stillman'}


How do you think that "Magic" happened? **Remember**, print() prints strings

Anonymous Objects

What is {1112: 'robert disalvo', 3001: 'janice blinoff', 1234: 'estandia fromm', 5192: 'gabor szabo', 9123: 'mihir ali'} 
called?

In [6]:
f"type = {type({1112: 'robert disalvo', 3001: 'janice blinoff', 1234: 'estandia fromm', 5192: 'gabor szabo', 9123: 'mihir ali'})}"

"type = <class 'dict'>"

In [7]:
f"id = {hex(id({1112: 'robert disalvo', 3001: 'janice blinoff', 1234: 'estandia fromm', 5192: 'gabor szabo', 9123: 'mihir ali'}))}"

'id = 0x1e790417b00'

There is no identifier (variable name) referencing (pointing to the dict object

## We can also refactor our program using try/except

In [9]:
people = {
    1112: "robert disalvo",
    3001: "janice blinoff",
    1234: "estandia fromm",
    5192: "gabor szabo",
    9123: "mihir ali"
    }

search_key = int(input("Enter a four-digit search key: "))

try:
    name = people[search_key]
    print(f"\nI found {search_key} in our database "
          f"with the name '{name}'")
except KeyError:
    ans = input(f"\n{search_key} is not in our database.  "
                f"Would you like to add it? ")
    if ans[0].upper() == 'Y':
        name = input(f"what name should we associate with {search_key}? ")
        people[search_key] = name

print(f"\nthe dictionary is currently: \n{str(people)}")

Enter a four-digit search key: 3000

3000 is not in our database.  Would you like to add it? y
what name should we associate with 3000? Jane Smith

the dictionary is currently: 
{1112: 'robert disalvo', 3001: 'janice blinoff', 1234: 'estandia fromm', 5192: 'gabor szabo', 9123: 'mihir ali', 3000: 'Jane Smith'}


Not only did this reduce our code by one statement, but it also captured name during the test (if it the key was found), so we wouldn't have to access the dictionary in our first print statement. Both the test key in dict and val = dict[key] are expensive method calls.

## Further operations involving Dictionaries

### in Operator

Consider a simple dict

In [10]:
my_dictionary = {"first" : 1, "second" : 2.2, "third" : "THREE"}

The **in** Operator
* searches the dict to determine if the key provided is in the dict

In [11]:
search_key = "second"
print("Key Found?", search_key in my_dictionary)
search_key = "sdf"
print("Key Found?", search_key in my_dictionary)
print()

Key Found? True
Key Found? False



The Bracket ([...]) Operator

In [12]:
my_dictionary = {"first" : 1, "second" : 2.2, "third" : "THREE"}

search_key = "second"
print(f"Value corresponding to the key {search_key} is {my_dictionary[search_key]}")
search_key = "third"
print(f"Value corresponding to the key {search_key} is {my_dictionary[search_key]}")

Value corresponding to the key second is 2.2
Value corresponding to the key third is THREE


## Looping through a Dictionary

Looping through a dict type is slightly different than looping through a list or str type. The key in each dict item is the thing over which we loop.

In [13]:
for key in my_dictionary:
    print(key) 

first
second
third


We cannot guarantee the order that our loop produces. Dictionaries, unlike lists, strings and tuples, are not ordered.  
* We can force a sort in our for loop, however, by calling sorted() on my_dictionary (this doesn't affect the actual order of the items in the dictionary) by using sorted() to sort the key in my_dictionary.

In [15]:
for key in sorted(my_dictionary):
    print(key)

first
second
third


In [16]:
sorted(my_dictionary)

['first', 'second', 'third']

Keep in mind, we are **not sorting** the dict, we are merely sorting the keys
* This has nothing to do with the actual order of the key/value pairs in the dict.

However, be careful: the only reason we got "first" before "second" was due to alphabetical ordering of the str type. Throw a "fourth" key into the list and things get crazy again:

In [18]:
my_dictionary = {"first" : 1, "second" : 2.2, "third" : "THREE",
                    "fourth" : 44.44}
for key in sorted(my_dictionary):
    print(key)

first
fourth
second
third


How did that work?

In [19]:
for var in my_dictionary:
    print(var)

first
second
third
fourth


In [20]:
for var in sorted(my_dictionary):
    print(var)

first
fourth
second
third


### A quick example of 3 important dict methods

#### The items() method

In [21]:
fruit = {"apple":"red", "bananna":"yellow", "lime":"green"}
fruit.items()

dict_items([('apple', 'red'), ('bananna', 'yellow'), ('lime', 'green')])

#### keys() method

In [22]:
fruit = {"apple":"red", "bananna":"yellow", "lime":"green"}
fruit.keys()

dict_keys(['apple', 'bananna', 'lime'])

#### the values() method

In [23]:
fruit = {"apple":"red", "bananna":"yellow", "lime":"green"}
fruit.values()

dict_values(['red', 'yellow', 'green'])

In [24]:
dict1 = {"first": ("apples", "oranges")}
print(dict1)

{'first': ('apples', 'oranges')}


In [25]:
dict1['first'][1]

'oranges'

Do not use dict if you need an ordering. There is another type that you can use when such predictability is required: **OrderedDict** (imported with the collections module).  We will not be using **OrderedDict** in this class.

The items() method

For more flexibility, you can turn the dictionary into a list of pairs (tuples) using the items() method which produces such a list.

In [26]:
for two_tuple in my_dictionary.items():
    print(two_tuple)

('first', 1)
('second', 2.2)
('third', 'THREE')
('fourth', 44.44)


items() gives you a way to pull out both keys and values in a single loop:

In [30]:
for my_key, my_val in  my_dictionary.items():
    print(my_key, my_val)
    print(type(my_key), type(my_val))

first 1
<class 'str'> <class 'int'>
second 2.2
<class 'str'> <class 'float'>
third THREE
<class 'str'> <class 'str'>
fourth 44.44
<class 'str'> <class 'float'>


### Quick Summary of the basic dict methods

keys()

In [28]:
my_dictionary.keys()

dict_keys(['first', 'second', 'third', 'fourth'])

values()

In [31]:
my_dictionary.values()

dict_values([1, 2.2, 'THREE', 44.44])

items()

In [32]:
my_dictionary.items()

dict_items([('first', 1), ('second', 2.2), ('third', 'THREE'), ('fourth', 44.44)])